name: Report Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install -g markdownlint-cli

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
          sudo apt-get install -y pandoc-citeproc
          sudo apt-get install -y texlive-xetex

      - name: Install BibTeX
        run: |
          sudo apt-get install -y bibtex2html

      - name: Check Markdown syntax
        run: npx markdownlint '**/*.md' || true

      - name: Check BibTeX syntax
        run: bibtexlint --glob '**/*.bib' || true

      - name: Set timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"

      - name: Compile Information Security Policy Framework to PDF
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          pandoc information-security-policy-framework.md --filter pandoc-citeproc -o "information-security-policy-framework-${{ steps.timestamp.outputs.timestamp }}.pdf"

      - name: Upload Information Security Policy Framework PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf-artifact
          path: "information-security-policy-framework-${{ steps.timestamp.outputs.timestamp }}.pdf"

      - name: Compile Executive Report to PDF
        run: |
          timestamp=$(date +"%Y%m%d%H%M%S")
          pandoc executive-report.md --filter pandoc-citeproc -o "executive-report-${{ steps.timestamp.outputs.timestamp }}.pdf"

      - name: Upload Executive Report PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: pdf-artifact
          path: "executive-report-${{ steps.timestamp.outputs.timestamp }}.pdf"
